name: content-management-system

on:
 push:
   branches: [ main ]
 workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
       - name: Get repository code
         uses: actions/setup-node@v3
       
       - name: Install dependencies
         run: npm ci
         env:
          NODE_DEBUG: "1"
         
       - name: Build the app
         run: npm run build
         
       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@v4
         with:
            folder: dist
    

  

  
